source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'DevApp' do
  pod 'GoogleMaps'
end

target 'UnitTest' do
  pod 'GoogleMaps'
  pod 'OCMock'
end

target 'GMUtils' do
  pod 'GoogleMaps'
end